FROM node:24.12-slim

WORKDIR /opt/microservices
COPY practica_creativa2/bookinfo/src/ratings/package.json .
COPY practica_creativa2/bookinfo/src/ratings/ratings.js .


ENV APP_VERSION=v1

RUN npm install

EXPOSE 9080
CMD ["node", "ratings.js", "9080"]