FROM python:3.9-slim


RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/CDPS-ETSIT/practica_creativa2.git

WORKDIR /practica_creativa2/bookinfo/src/productpage


RUN pip3 install -r requirements.txt


ENV TEAM_ID=3
EXPOSE 9080


CMD ["python3", "productpage.py", "9080"]