apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v3
  namespace: cdps-3
  labels:
    app: reviews
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v3
  template:
    metadata:
      labels:
        app: reviews
        version: v3
    spec:
      containers:
      - name: reviews
        image: cdps-reviews:g3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        env:
        - name: SERVICE_VERSION
          value: "v3"
        - name: ENABLE_RATINGS
          value: "true"
        - name: STAR_COLOR
          value: "red"