apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  namespace: cdps-3
  labels:
    app: reviews
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      containers:
      - name: reviews
        image: cdps-reviews:g3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        env:
        - name: SERVICE_VERSION
          value: "v1"
        - name: ENABLE_RATINGS
          value: "false"
        - name: STAR_COLOR
          value: "black"